package model;
// Generated 27/04/2019 21:52:51 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

    private int categoryId;

    @NotEmpty(message = "Campo obrigatorio")
    @Size(min = 4, max = 20, message = "Descrição deve ter no máximo {10} caracteres"
            + " e no minimo" + " {4} caracteres."
            + " Você digitou: " + "${validatedValue}")
    private String name;

    private Date lastUpdate = new Date(System.currentTimeMillis());
    private Set<FilmCategory> filmCategories = new HashSet<FilmCategory>(0);

    public Category() {
    }

    public Category(int categoryId, String name, Date lastUpdate) {
        this.categoryId = categoryId;
        this.name = name;
        this.lastUpdate = lastUpdate;
    }

    public Category(int categoryId, String name, Date lastUpdate, Set<FilmCategory> filmCategories) {
        this.categoryId = categoryId;
        this.name = name;
        this.lastUpdate = lastUpdate;
        this.filmCategories = filmCategories;
    }

    public int getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public Set<FilmCategory> getFilmCategories() {
        return this.filmCategories;
    }

    public void setFilmCategories(Set<FilmCategory> filmCategories) {
        this.filmCategories = filmCategories;
    }

}
